//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTeknikServisEntities : DbContext
    {
        public DbTeknikServisEntities()
            : base("name=DbTeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMINs { get; set; }
        public virtual DbSet<TBLARACLAR> TBLARACLARs { get; set; }
        public virtual DbSet<TBLARIZADETAY> TBLARIZADETAYs { get; set; }
        public virtual DbSet<TBLCARI> TBLCARIs { get; set; }
        public virtual DbSet<TBLDEPARTMAN> TBLDEPARTMen { get; set; }
        public virtual DbSet<TBLFATURABILGI> TBLFATURABILGIs { get; set; }
        public virtual DbSet<TBLFATURADETAY> TBLFATURADETAYs { get; set; }
        public virtual DbSet<TBLGIDER> TBLGIDERs { get; set; }
        public virtual DbSet<TBLKATEGORI> TBLKATEGORIs { get; set; }
        public virtual DbSet<TBLNOTLARIM> TBLNOTLARIMs { get; set; }
        public virtual DbSet<TBLPERSONEL> TBLPERSONELs { get; set; }
        public virtual DbSet<TBLURUN> TBLURUNs { get; set; }
        public virtual DbSet<TBLURUNHAREKET> TBLURUNHAREKETs { get; set; }
        public virtual DbSet<TBLURUNTAKIP> TBLURUNTAKIPs { get; set; }
        public virtual DbSet<TLBURUNKABUL> TLBURUNKABULs { get; set; }
    }
}
